### ISSUE TITLE
Error: can't update to writable. you don't have permission"

### ISSUE THREAD

**Issue by RonakPustack** [netless-io/whiteboard-android#13]
Upon joining a classroom with roomToken generated with role "reader".
The SDK throws exception: "[White] Error: can't update to writable. you don't have permission".

![error](https://user-images.githubusercontent.com/68676516/156739628-4d504c30-5529-4a98-87b0-1b3539f1ff50.png)

**Comment by leavesster** [comment]
Your 'reader' room token ,can't change to writable state. Only 'write' room token can change to writable.

If you want to join room with 'reader' room token, you need set `roomParams`'s `isWritable` property to false which is default true.
