### ISSUE TITLE
Error: Autofill is disabled: AutofillManager isn't available in given Context

### ISSUE THREAD

**Issue by DavidSonNguyen** [netless-io/whiteboard-android#14]
I use Android version 2.16.23
When I use the Text tool, the keyboard appears and disappears immediately.
And I got the error `Autofill is disabled: AutofillManager isn't available in given Context`
Device: Android 11
Whiteboard version: 2.16.23

**Comment by aderan** [comment]
@DavidSonNguyen We have tested several phones with Autofill enabled and disabled. the above phenomenon did not recur. This problem looks more like a View Focus issue. Maybe you can clone and try [this example](https://github.com/netless-io/fastboard-android). 
if the issue persists, we need more your devices info:
- Device Info (e.g. Samsung Galaxy Tab S6/One UI 4.0, Redmi Note 11/MIUI 12.5)
- WebView Version (at developer options -> WebView Implementation)

also, you may run your sample on other devices or android emulator to get more info.
